### ISSUE TITLE
Transfer Commands

### ISSUE THREAD

**Issue by holycrab13** [dbpedia/databus-transfer#2]
databus.dbpedia.org/dbpedia ----> databus.dbpedia.org/dbpedia

**Comment by devanshkansagra** [comment]
Can you explain this issue? So that I can resolve this

**Comment by manonthegithub** [comment]
@holycrab13 could you give some comments on that issue?

**Comment by holycrab13** [comment]
My bad, didn't close this. Both old databus instances have been migrated, so this issue (and probably the repo) is no longer neede.
